-- Ejecuta este archivo completo en Supabase > SQL Editor > New query > Run

create table if not exists public.claims_book (
  id bigint generated by default as identity primary key,
  claim_code text not null unique,
  consumer_name text not null,
  document_type text not null check (document_type in ('DNI', 'CE', 'Pasaporte')),
  document_number text not null,
  consumer_address text not null,
  department text not null,
  province text not null,
  district text not null,
  email text not null,
  phone text not null,
  is_minor boolean not null default false,
  guardian_name text,
  contracted_item_type text not null check (contracted_item_type in ('producto', 'servicio')),
  order_number text,
  contracted_item_description text not null,
  claimed_amount numeric(12,2),
  claim_type text not null check (claim_type in ('reclamo', 'queja')),
  claim_detail text not null,
  consumer_request text not null,
  accepted_declaration boolean not null default false,
  status text not null default 'pendiente' check (status in ('pendiente', 'en_revision', 'respondido', 'cerrado')),
  response text,
  responded_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.claims_book enable row level security;

drop policy if exists "Public can create claims" on public.claims_book;
create policy "Public can create claims"
on public.claims_book
for insert
to anon, authenticated
with check (accepted_declaration = true);

create index if not exists claims_book_claim_code_idx on public.claims_book(claim_code);
create index if not exists claims_book_created_at_idx on public.claims_book(created_at desc);
create index if not exists claims_book_status_idx on public.claims_book(status);
