-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.product_combos (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text,
  image_url text,
  product_ids jsonb not null default '[]'::jsonb,
  combo_price numeric(10,2),
  badge text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.product_combos enable row level security;
drop policy if exists "Public can read active combos" on public.product_combos;
create policy "Public can read active combos" on public.product_combos for select
to anon, authenticated
using (
  is_active = true
  or exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.role = 'admin' and coalesce(pr.is_active, true) = true)
);
drop policy if exists "Admins manage combos" on public.product_combos;
create policy "Admins manage combos" on public.product_combos for all
to authenticated
using (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.role = 'admin' and coalesce(pr.is_active, true) = true))
with check (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.role = 'admin' and coalesce(pr.is_active, true) = true));

create table if not exists public.athletes (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sport_role text not null default 'Atleta',
  brand text,
  excerpt text,
  content text,
  cover_image_url text,
  product_image_url text,
  featured boolean not null default false,
  status text not null default 'draft' check (status in ('draft','published')),
  sort_order integer not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.athletes enable row level security;
drop policy if exists "Public can read published athletes" on public.athletes;
create policy "Public can read published athletes" on public.athletes for select
to anon, authenticated
using (
  status = 'published'
  or exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.role = 'admin' and coalesce(pr.is_active, true) = true)
);
drop policy if exists "Admins manage athletes" on public.athletes;
create policy "Admins manage athletes" on public.athletes for all
to authenticated
using (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.role = 'admin' and coalesce(pr.is_active, true) = true))
with check (exists (select 1 from public.profiles pr where pr.id = auth.uid() and pr.role = 'admin' and coalesce(pr.is_active, true) = true));

-- El dueño no quiere Bolsos/Mochilas: migrar todo a Rodilleras.
update public.products set category = 'rodilleras' where lower(category) in ('bolsos','bolsos-y-mochilas','mochilas');

do $$
begin
  if exists (select 1 from public.categories where slug = 'rodilleras') then
    delete from public.categories where slug in ('bolsos','bolsos-y-mochilas','mochilas');
  else
    update public.categories
       set name = 'Rodilleras', slug = 'rodilleras', image_url = null, updated_at = now()
     where slug in ('bolsos','bolsos-y-mochilas','mochilas');
  end if;
end $$;

insert into public.categories (name, slug, image_url, is_active, show_home, sort_order)
select 'Rodilleras', 'rodilleras', null, true, true, 30
where not exists (select 1 from public.categories where slug = 'rodilleras');
