import LegalPage, { LegalList } from "./LegalPage";
export default function About(){return <LegalPage eyebrow="Quiénes somos" title="Quiénes Somos" subtitle="Pasión por el deporte. Compromiso con la calidad. The House of Sports nace de una pasión compartida por el fútbol, el deporte y la búsqueda constante de productos que realmente marquen la diferencia." icon="about" sections={[
{title:"Nuestra historia",content:<><h3 className="font-black uppercase">Una pasión que se convirtió en THS</h3><p className="mt-3">The House of Sports nació en 2024, fundada por padre e hijo unidos por una misma pasión: el fútbol y el deporte.</p><p className="mt-3">Nuestra historia comenzó con la llegada de POKER al Perú, una reconocida marca brasileña especializada en guantes de arquero. Aquella primera representación dio inicio a un proyecto mucho más grande: construir una casa que reúna marcas internacionales capaces de ofrecer verdadera calidad y rendimiento al deportista peruano.</p><p className="mt-3">En 2025 incorporamos 181 KEEPERS, marca portuguesa especializada en protecciones deportivas de alto rendimiento. En 2026 llegó TLSS, marca asiática enfocada en calzado de fútbol con tecnología, materiales premium y soluciones para diferentes estilos de juego.</p><p className="mt-3">Hoy, POKER, 181 KEEPERS y TLSS representan los tres pilares sobre los que seguimos construyendo The House of Sports.</p></>},
{title:"Nuestra propuesta",content:<><h3 className="font-black uppercase">No buscamos crecer por crecer. Buscamos crecer con las mejores marcas.</h3><p className="mt-3">Queremos construir una propuesta deportiva cada vez más completa para el mercado peruano, incorporando marcas internacionales que destaquen por su calidad, tecnología, innovación y rendimiento.</p><p className="mt-3">Buscamos marcas con identidad propia y productos que aporten beneficios reales. Nuestra propuesta es acercar al Perú lo mejor del deporte internacional y convertir THS en una casa donde cada nueva marca sume valor, innovación y nuevas posibilidades para el deportista.</p></>},
{title:"Qué nos diferencia",content:<LegalList items={["REPRESENTACIÓN OFICIAL — Representamos oficialmente en el Perú a las marcas que forman parte de THS.","SELECCIÓN ESPECIALIZADA — Evaluamos calidad, tecnología, materiales, rendimiento y necesidades reales del deportista.","PRODUCTOS 100% ORIGINALES — Trabajamos únicamente con productos originales de nuestras marcas representadas.","ASESORÍA REAL — Explicamos tecnologías, materiales y diferencias para ayudarte a elegir correctamente.","UNA EXPERIENCIA MÁS ALLÁ DE LA VENTA — Buscamos construir una comunidad alrededor del deporte y acompañar al cliente después de su compra."]}/>},
{title:"Misión y visión",content:<><h3 className="font-black uppercase">Nuestra misión</h3><p className="mt-2">Acercar al deportista peruano marcas internacionales de alta calidad, tecnología e innovación, ofreciendo equipamiento especializado que contribuya a mejorar su rendimiento, confianza y experiencia deportiva, acompañado de asesoría y una compra cercana y confiable.</p><h3 className="mt-6 font-black uppercase">Nuestra visión</h3><p className="mt-2">Convertir a The House of Sports en una de las principales referencias de equipamiento deportivo especializado del Perú, reconocida por representar marcas internacionales innovadoras y elevar constantemente el estándar de calidad disponible en nuestro mercado.</p></>},
{title:"Nuestros valores",content:<LegalList items={["PASIÓN — El deporte es el origen de THS y el motor detrás de cada decisión.","CALIDAD — Preferimos seleccionar menos marcas, pero trabajar con productos en los que realmente creemos.","INNOVACIÓN — Buscamos nuevas tecnologías, materiales y propuestas que aporten algo diferente.","CONFIANZA — Construimos relaciones de largo plazo con productos originales, información clara y atención responsable.","COMPROMISO — Con nuestras marcas, clientes y el crecimiento del deporte en el Perú."]}/>},
{title:"Compromiso social",content:<><h3 className="font-black uppercase">Nuestro compromiso va más allá del deporte</h3><p className="mt-3">The House of Sports nace dentro de una familia que entiende que crecer también significa generar un impacto positivo en los demás.</p><p className="mt-3">Nuestra familia impulsa una fundación sin fines de lucro dedicada a apoyar a niños y familias en situación de extrema vulnerabilidad en el Perú.</p><p className="mt-3">Este compromiso social forma parte de nuestros valores: crecer con propósito, generar oportunidades y recordar que detrás de cualquier proyecto siempre existen personas.</p></>}
]}/>}
