import { useEffect, useState } from "react";
import { ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { supabase } from "../lib/supabase";

export default function Athletes(){const [items,setItems]=useState<any[]>([]);useEffect(()=>{supabase.from("athletes").select("*").eq("status","published").order("featured",{ascending:false}).order("sort_order").then(({data})=>setItems(data??[]))},[]);return <div className="min-h-screen bg-[#090a0b] text-white"><Header onSearch={()=>{}}/><main>
<section className="border-b border-white/10 bg-[radial-gradient(circle_at_80%_10%,rgba(227,38,46,.22),transparent_35%),linear-gradient(180deg,#111315,#090a0b)] py-16 lg:py-24"><div className="padel-container"><p className="text-[11px] font-black uppercase tracking-[.18em] text-[#e3262e]">Blog de atletas THS</p><h1 className="mt-3 max-w-4xl text-4xl font-black uppercase italic tracking-[-.05em] sm:text-5xl lg:text-6xl">Referentes que viven el deporte al máximo nivel</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-white/60">Conoce sus historias, trayectoria, equipamiento y la relación que construyen con las marcas seleccionadas por The House of Sports.</p></div></section>
<section className="py-12 lg:py-16"><div className="padel-container"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(a=><Link key={a.id} to={`/atletas/${a.slug}`} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#121416] transition hover:-translate-y-1 hover:border-[#e3262e]/60"><div className="relative aspect-[4/3] overflow-hidden bg-black"><img src={a.cover_image_url||""} alt={a.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent"/><span className="absolute left-4 top-4 rounded bg-[#e3262e] px-2 py-1 text-[9px] font-black uppercase">{a.brand||"THS"}</span></div><div className="p-5"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#e3262e]">{a.sport_role}</p><h2 className="mt-2 text-2xl font-black uppercase">{a.name}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-white/55">{a.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-black uppercase">Ver historia <ArrowRight size={14}/></span></div></Link>)}</div>{items.length===0&&<p className="py-16 text-center text-white/45">Próximamente conocerás a los atletas y referentes de THS.</p>}</div></section>
</main><Footer/></div>}
