import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { supabase } from "../lib/supabase";

export default function AthletePost(){const {slug}=useParams();const [a,setA]=useState<any>(null);const [loading,setLoading]=useState(true);useEffect(()=>{if(!slug)return;supabase.from("athletes").select("*").eq("slug",slug).eq("status","published").single().then(({data})=>{setA(data);setLoading(false)})},[slug]);if(loading)return <div className="min-h-screen bg-[#090a0b]"/>;if(!a)return <div className="min-h-screen bg-[#090a0b] text-white"><Header onSearch={()=>{}}/><div className="padel-container py-24 text-center"><h1 className="text-3xl font-black">Atleta no encontrado</h1><Link to="/atletas" className="mt-6 inline-block text-[#e3262e]">Volver a atletas</Link></div><Footer/></div>;
return <div className="min-h-screen bg-white text-neutral-950"><Header onSearch={()=>{}}/><main><section className="py-10 lg:py-16"><div className="padel-container"><Link to="/atletas" className="mb-8 inline-flex items-center gap-2 text-xs font-black uppercase text-neutral-500"><ArrowLeft size={14}/> Todos los atletas</Link><div className="grid items-center gap-10 lg:grid-cols-[.95fr_1.15fr] lg:gap-16"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#e3262e]">{a.sport_role}</p><h1 className="mt-3 text-4xl font-black uppercase tracking-[-.05em] sm:text-5xl">{a.name}</h1><h2 className="mt-2 text-2xl font-bold text-neutral-400">{a.brand&&`Representante ${a.brand}`}</h2>{a.excerpt&&<p className="mt-8 max-w-xl text-base leading-8 text-neutral-700">{a.excerpt}</p>}<a href={`/marcas`} className="mt-7 inline-flex items-center gap-2 rounded-full bg-black px-6 py-3 text-xs font-black uppercase text-white">Conoce la marca <ArrowRight size={14}/></a></div><div className="relative mx-auto w-full max-w-[620px]"><img src={a.cover_image_url} alt={a.name} className="aspect-[4/5] w-[78%] rounded-xl object-cover shadow-2xl"/>{a.product_image_url&&<div className="absolute bottom-[12%] right-0 w-[38%] overflow-hidden rounded-xl border border-neutral-200 bg-white p-2 shadow-xl"><img src={a.product_image_url} alt={`Equipamiento de ${a.name}`} className="aspect-square w-full object-cover"/></div>}</div></div></div></section><section className="border-t border-neutral-100 bg-neutral-50 py-12 lg:py-16"><div className="mx-auto max-w-3xl px-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#e3262e]">Historia THS</p><div className="mt-5 whitespace-pre-line text-[15px] leading-8 text-neutral-700">{a.content}</div></div></section></main><Footer/></div>}
