import LegalPage,{LegalList} from "./LegalPage";
export default function Privacy(){return <LegalPage eyebrow="Protección de datos" title="Política de Privacidad y Protección de Datos Personales" subtitle="Información sobre el tratamiento de datos recopilados a través de thehouseofsports.pe." updated="Agosto 2026" icon="privacy" sections={[
{title:"Responsable",content:<p>Responsable actual: Claudio Bellido Bejar · RUC: 10422446503 · Domicilio: Ca. Junin Urb. Alejandro Alvarez Mz. C Lt. 11B, Ate, Lima, Lima · Correo: admi.ths.pe@gmail.com · WhatsApp: 993 834 954.</p>},
{title:"Información que podemos recopilar",content:<LegalList items={["Nombre y apellidos.","DNI/RUC cuando corresponda para facturación.","Correo electrónico y número telefónico.","Dirección de entrega, distrito, provincia y departamento.","Información de pedidos e historial de compras.","Comunicaciones con THS e información para cambios, garantías o reclamos.","Información técnica de navegación como IP, dispositivo y cookies cuando corresponda."]}/>},
{title:"Información de pagos",content:<p>Los pagos con tarjeta son procesados mediante proveedores especializados como Culqi. THS no debe solicitar mediante canales informales contraseñas bancarias, claves secretas ni códigos de seguridad personales. Culqi declara utilizar mecanismos de seguridad y cumplimiento PCI DSS para datos sensibles de tarjetas.</p>},
{title:"¿Para qué utilizamos tus datos?",content:<LegalList items={["Procesar compras y pagos y emitir comprobantes.","Preparar y entregar pedidos y contactar al cliente respecto a una compra.","Gestionar personalizaciones, cambios, devoluciones y garantías.","Atender consultas y reclamos.","Prevenir operaciones fraudulentas y cumplir obligaciones legales y tributarias.","Mejorar el servicio y funcionamiento de la página.","Enviar promociones solo cuando el usuario haya otorgado el consentimiento correspondiente."]}/>},
{title:"Comunicaciones comerciales",content:<><p>La compra de un producto no obliga al usuario a suscribirse a publicidad. La autorización para recibir promociones, lanzamientos o comunicaciones publicitarias debe presentarse de manera diferenciada, ser opcional y poder retirarse posteriormente.</p></>},
{title:"Proveedores y terceros",content:<LegalList items={["Pasarelas y procesadores de pago.","Empresas de courier y transporte.","Proveedores de alojamiento y tecnología.","Servicios de correo y comunicaciones.","Servicios contables o administrativos.","Autoridades cuando exista obligación legal."]}/>},
{title:"Seguridad",content:<p>THS adoptará medidas razonables para evitar acceso, alteración, pérdida o uso no autorizado de los datos. Ningún sistema garantiza seguridad absoluta, pero buscamos trabajar con servicios tecnológicos adecuados para reducir estos riesgos.</p>},
{title:"Cookies",content:<><p>La página puede utilizar cookies para mantener sesiones, recordar carrito, medir funcionamiento, analizar navegación, personalizar experiencia y publicidad cuando corresponda.</p><p className="mt-3">Las cookies no esenciales deberán gestionarse conforme a los mecanismos de consentimiento aplicables.</p></>},
{title:"Derechos del titular",content:<><LegalList items={["Acceso a sus datos.","Rectificación y actualización.","Cancelación.","Oposición al tratamiento.","Revocación del consentimiento cuando proceda."]}/><p className="mt-3">Las solicitudes pueden dirigirse a admi.ths.pe@gmail.com. La normativa peruana exige además la inscripción de los bancos de datos personales correspondientes ante la Autoridad Nacional de Protección de Datos Personales.</p></>},
{title:"Menores de edad",content:<p>THS comercializa productos que pueden ser utilizados por menores, pero la contratación y entrega de datos para realizar compras deberá ser efectuada por una persona con capacidad para contratar o bajo responsabilidad de su representante.</p>},
{title:"Conservación",content:<p>La información se conservará durante el tiempo necesario para las finalidades para las que fue recopilada y posteriormente durante los períodos exigidos por obligaciones legales, contables, tributarias o de defensa frente a reclamaciones. Los datos usados solo para marketing podrán dejar de utilizarse cuando el titular retire su consentimiento.</p>},
{title:"Actualizaciones",content:<p>Esta Política podrá modificarse para adaptarse a cambios legales, técnicos o comerciales. La versión vigente estará siempre disponible en nuestra página web.</p>}
]}/>}
