import LegalPage,{LegalList} from "./LegalPage";
export default function Returns(){return <LegalPage eyebrow="Cambios, devoluciones y garantías" title="Cambios, Devoluciones y Garantías" subtitle="Queremos que el producto que recibas sea el adecuado para ti. Por ello establecemos condiciones claras para cambios, devoluciones y garantías." updated="Agosto 2026" icon="returns" sections={[
{title:"Plazo para solicitar un cambio",content:<><p>Las solicitudes deben realizarse dentro de los <b>7 días calendario</b> siguientes a la recepción.</p><p className="mt-3">WhatsApp: 993 834 954 · Correo: admi.ths.pe@gmail.com. Indica número de pedido, producto, motivo y fotografías cuando sean solicitadas.</p></>},
{title:"Condiciones generales",content:<LegalList items={["Producto completamente nuevo y sin uso.","Sin desgaste, suciedad, manchas, olores ni alteraciones.","Con etiquetas, caja, bolsa, envoltura, accesorios y empaques originales.","No personalizado y dentro del plazo establecido.","THS evaluará el producto antes de aprobar definitivamente el cambio."]}/>},
{title:"¿Qué significa sin uso?",content:<LegalList items={["Guantes: solo pueden probarse para talla y ajuste; entrenar, jugar, tocar balón o desgastar el látex se considera uso.","Calzado: probar únicamente en superficie interior y limpia; sin tierra ni marcas de uso deportivo.","Rodilleras, coderas y protecciones: probar para ajuste, sin entrenamiento, sudor, olor, suciedad o desgaste.","Ropa y accesorios: sin lavado, manchas, olores, modificaciones ni evidencia de uso."]}/>},
{title:"Costos de cambio por talla o modelo",content:<p>Si el cambio responde a una decisión del cliente, este asume el transporte hacia THS y el nuevo envío; también puede coordinar cambio presencial en Ate. Si existe error atribuible a THS o defecto aprobado, THS asumirá los costos razonables correspondientes.</p>},
{title:"Diferencias de precio",content:<p>Si el nuevo producto cuesta más, el cliente abonará la diferencia. Si cuesta menos, podrá coordinarse devolución de la diferencia o nota de crédito/saldo aplicable.</p>},
{title:"Productos personalizados",content:<><p>No califican para cambios por talla, modelo, diseño, error del cliente o cambio de opinión. Antes de confirmar revisa talla, nombre, texto, número, ortografía y diseño.</p><p className="mt-3">Una vez iniciada la personalización tampoco podrá cancelarse ordinariamente, salvo defecto de fabricación o error de personalización atribuible a THS.</p></>},
{title:"Productos en oferta, liquidación o venta final",content:<p>Los productos identificados expresamente como LIQUIDACIÓN, VENTA FINAL o NO APLICA CAMBIOS no aceptan cambios ordinarios por talla o modelo cuando esta condición fue informada antes de la compra. Esto no excluye defectos de fabricación o errores de despacho.</p>},
{title:"Combos y promociones",content:<LegalList items={["Un cambio de talla por el mismo producto y precio puede realizarse sin afectar el resto del combo, sujeto a stock.","Si el cambio modifica productos, precios o condiciones del descuento, THS podrá recalcular el beneficio.","Si una devolución afecta la promoción completa, puede ser necesario devolver productos o beneficios asociados."]}/>},
{title:"Devoluciones y reembolsos",content:<><p>THS no realiza reembolsos automáticos por cambio de opinión. Podrán evaluarse reparación, cambio, nota de crédito o reembolso por producto incorrecto, talla errónea por THS, producto incompleto, defecto de fabricación, producto que no corresponda a lo ofrecido u otra situación procedente.</p></>},
{title:"Garantía comercial THS",content:<><p>THS ofrece una garantía comercial de <b>30 días calendario</b> desde la recepción por defectos de fabricación, independiente del período ordinario de 7 días para cambios.</p><LegalList items={["No cubre desgaste normal, superficies no recomendadas, daños accidentales, cortes, perforaciones o abrasión.","No cubre lavado/mantenimiento incorrecto, químicos o calor, modificaciones por terceros o uso contrario al fabricante.","El desgaste progresivo del látex de guantes por contacto con balón y superficie es desgaste natural.","THS puede solicitar fotos, videos y entrega física; procurará comunicar el resultado en aproximadamente 5 días hábiles."]}/></>},
{title:"Reembolsos aprobados",content:<p>Cuando corresponda, THS buscará usar el mismo medio de pago cuando sea técnicamente posible. En tarjeta, el extorno depende de la pasarela y banco emisor; para Yape, Plin o transferencia podrán solicitarse datos del titular. El tiempo final depende del medio de pago.</p>}
]}/>}
