import LegalPage,{LegalList} from "./LegalPage";
export default function Shipping(){return <LegalPage eyebrow="Envíos a todo el Perú" title="Política de Envíos" subtitle="Queremos que tu pedido llegue de manera segura y con información clara desde el momento de la compra." updated="Agosto 2026" icon="shipping" sections={[
{title:"Preparación de pedidos",content:<p>Los pedidos comienzan a procesarse una vez confirmado el pago. Los plazos son estimados y pueden variar por campañas, feriados, alta demanda o situaciones externas. Los productos personalizados pueden requerir tiempo adicional.</p>},
{title:"Envíos regulares a Lima Metropolitana y Callao",content:<><p><b>Tarifa: S/15.</b> Tiempo estimado: 1 a 3 días hábiles. Todos los pedidos salen desde nuestra sede central en Ate, Lima.</p><p className="mt-3">El cliente es responsable de registrar correctamente dirección, distrito, teléfono y referencias.</p></>},
{title:"Envío Express",content:<><p>Disponible únicamente para Lima Metropolitana y Callao. Permite coordinar entrega dentro de las siguientes 24 horas, sujeto a disponibilidad logística.</p><LegalList items={["Tarifa variable según distrito y distancia desde Ate.","Depende del día, hora y disponibilidad del transporte.","Debe consultarse, cotizarse y confirmarse previamente por WhatsApp al 993 834 954.","No está incluido en promociones de envío gratuito salvo indicación expresa."]}/></>},
{title:"Envíos a provincia",content:<><p><b>Tarifa regular: S/20.</b> Los pedidos pueden despacharse mediante Shalom, Olva Courier, Marvisur u otras agencias disponibles. La modalidad regular contempla principalmente recojo en agencia; la entrega a domicilio podrá coordinarse cuando el operador la ofrezca y cualquier costo adicional será informado.</p></>},
{title:"Envío gratuito",content:<><p className="font-black">Compras superiores a S/400: ENVÍO REGULAR GRATIS A TODO EL PERÚ.</p><LegalList items={["En Lima aplica al envío regular.","En provincias aplica al despacho regular mediante agencia.","No incluye envío Express, recargos extraordinarios, servicios especiales ni costos adicionales de entrega domiciliaria provincial."]}/></>},
{title:"Recojo en sede central",content:<p>El cliente puede recoger gratuitamente su pedido en nuestra sede de Ate una vez que THS confirme que está preparado. Recomendamos coordinar previamente por WhatsApp.</p>},
{title:"Dirección incorrecta o ausencia del destinatario",content:<><p>Si el pedido no puede entregarse por dirección incorrecta o incompleta, ausencia, teléfono sin respuesta o datos incorrectos proporcionados por el cliente, un segundo despacho podrá generar un nuevo costo de envío.</p></>},
{title:"Incidencias durante el transporte",content:<p>Si identificas pérdida, daño visible, retraso extraordinario u otra incidencia, comunícate con THS lo antes posible. Brindaremos la información y asistencia disponible para gestionar el caso con el operador correspondiente.</p>}
]}/>}
