import LegalPage,{LegalList} from "./LegalPage";
export default function Terms(){return <LegalPage eyebrow="Páginas legales" title="Términos y Condiciones de Uso y Compra" subtitle="Reglas aplicables al uso de thehouseofsports.pe y a las compras realizadas en The House of Sports – THS." updated="Agosto 2026" icon="terms" sections={[
{title:"Identificación",content:<p>El sitio thehouseofsports.pe es operado comercialmente bajo el nombre The House of Sports – THS. Titular: Claudio Bellido Bejar · RUC: 10422446503 · Domicilio: Ca. Junin Urb. Alejandro Alvarez Mz. C Lt. 11B, Ate, Lima, Lima · Correo: admi.ths.pe@gmail.com · WhatsApp: 993 834 954. Estos datos podrán actualizarse cuando se complete la reorganización societaria de la empresa.</p>},
{title:"Uso del sitio",content:<p>Al navegar, registrarse o comprar en nuestra web, el usuario declara haber leído y aceptado estos Términos y Condiciones y las políticas relacionadas aplicables.</p>},
{title:"Productos",content:<><p>THS busca mostrar con precisión características, fotografías, colores, tallas, materiales, tecnologías, precios y disponibilidad.</p><p className="mt-3">Las fotografías son referenciales y pueden existir variaciones menores de tonalidad por iluminación, pantalla o lote de fabricación.</p></>},
{title:"Disponibilidad y stock",content:<p>La inclusión de un producto no garantiza de manera absoluta su disponibilidad hasta procesar la orden. Ante una inconsistencia excepcional de stock después del pago, THS contactará al cliente para ofrecer cambio, espera de reposición, nota de crédito o reembolso correspondiente.</p>},
{title:"Precios",content:<p>Todos los precios se muestran en soles peruanos (S/). Promociones y descuentos pueden estar sujetos a vigencia, stock limitado y condiciones particulares. El costo de envío se informará antes de completar la compra cuando corresponda.</p>},
{title:"Pagos",content:<><p>THS acepta los medios habilitados en cada momento, entre ellos tarjetas, Yape, Plin y transferencias bancarias. Los pagos con tarjeta son procesados mediante Culqi.</p><p className="mt-3">THS nunca solicitará por WhatsApp, redes sociales o correo la clave secreta de una tarjeta, CVV, contraseña bancaria ni código de seguridad personal.</p></>},
{title:"Confirmación del pedido",content:<LegalList items={["La recepción automática de una orden no implica necesariamente aceptación final.","La orden queda sujeta a confirmación del pago.","Validación de stock e información necesaria.","Controles de seguridad cuando correspondan."]}/>},
{title:"Cancelaciones",content:<p>El cliente puede solicitar cancelación antes del despacho y antes de iniciar cualquier personalización. Una vez despachado aplica la Política de Cambios y Devoluciones; iniciada la personalización no procede la cancelación ordinaria.</p>},
{title:"Personalizaciones",content:<p>El cliente es responsable de verificar la información proporcionada. THS podrá rechazar solicitudes con contenido ilegal, ofensivo, discriminatorio o que razonablemente vulnere derechos de terceros. Las condiciones de cambios y garantías se detallan en la política correspondiente.</p>},
{title:"Envíos",content:<p>Los envíos están sujetos a nuestra Política de Envíos. Los plazos son estimados y pueden verse afectados por logística del transportista, feriados, fenómenos naturales, bloqueos, alta demanda u otros eventos extraordinarios.</p>},
{title:"Promociones",content:<p>Cada promoción puede tener vigencia, stock, productos participantes, exclusiones, límites de uso y condiciones específicas. Cupones y descuentos no necesariamente son acumulables salvo indicación contraria.</p>},
{title:"Cambios, devoluciones y garantías",content:<p>Estas solicitudes se rigen por nuestra Política de Cambios, Devoluciones y Garantías y por la legislación aplicable.</p>},
{title:"Propiedad intelectual",content:<p>El contenido propio de THS, incluyendo diseños, fotografías, textos e identidad gráfica, no podrá utilizarse comercialmente sin autorización. Las marcas de terceros pertenecen a sus respectivos titulares.</p>},
{title:"Modificaciones",content:<p>THS podrá actualizar estos Términos y Condiciones por cambios operativos, tecnológicos, comerciales o normativos. La versión vigente será la publicada en el sitio.</p>},
{title:"Atención al cliente y reclamos",content:<p>Consultas: admi.ths.pe@gmail.com · 993 834 954. THS mantiene accesible el Libro de Reclamaciones. El plazo vigente para atender reclamos y quejas presentados mediante el Libro es de hasta 15 días hábiles no prorrogables.</p>}
]}/>}
