import { useEffect, useState } from "react";
import { Award, ShieldCheck, HeartHandshake, ArrowRight } from "lucide-react";
import { Link } from "react-router-dom";
import logo1 from "../assets/trust1.jpg";
import logo2 from "../assets/trust2.jpg";
import logo3 from "../assets/trust3.jpg";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, EffectFade } from "swiper/modules";
import { supabase } from "../lib/supabase";
import "swiper/css";
import "swiper/css/effect-fade";
const fallback=[logo1,logo2,logo3];
const items=[{icon:Award,title:"Especialistas",desc:"Equipamiento seleccionado para arqueros y jugadores."},{icon:ShieldCheck,title:"Calidad",desc:"Marcas originales con tecnología y alto rendimiento."},{icon:HeartHandshake,title:"Compromiso",desc:"Contigo dentro y fuera de la cancha."}];
export default function Trust(){const [images,setImages]=useState<string[]>(fallback);useEffect(()=>{supabase.from("athletes").select("cover_image_url").eq("status","published").not("cover_image_url","is",null).order("featured",{ascending:false}).order("sort_order").limit(5).then(({data})=>{const urls=(data??[]).map((a:any)=>a.cover_image_url).filter(Boolean);if(urls.length)setImages(urls)})},[]);return <section className="bg-white py-12 lg:py-16"><div className="padel-container"><div className="overflow-hidden rounded-[8px] bg-neutral-950"><div className="grid lg:grid-cols-[1fr_0.95fr]"><div className="p-8 text-white lg:p-12"><p className="text-[12px] font-black uppercase tracking-[0.16em] text-[#e3262e]">Nuestros atletas</p><h2 className="mt-5 text-[30px] font-black uppercase tracking-[-0.04em] lg:text-[38px]">Quienes compiten al máximo nivel eligen las mejores marcas</h2><p className="mt-5 max-w-xl text-[14px] leading-[1.9] text-white/70">En THS seleccionamos marcas internacionales reconocidas por su calidad, tecnología y rendimiento, presentes junto a atletas y profesionales que compiten al más alto nivel. POKER, TLSS y 181 KEEPERS son elegidas por deportistas que exigen lo mejor de su equipamiento. Descubre a algunos de sus grandes referentes y las marcas que los acompañan en cada desafío.</p><Link to="/atletas" className="mt-8 inline-flex items-center gap-2 bg-[#e3262e] px-7 py-3 text-[12px] font-black uppercase text-white hover:bg-[#bd1720]">Conoce a los referentes <ArrowRight size={15}/></Link></div><div className="relative min-h-[320px] overflow-hidden"><Swiper modules={[Autoplay,EffectFade]} effect="fade" fadeEffect={{crossFade:true}} slidesPerView={1} loop={images.length>1} speed={1000} autoplay={{delay:2500,disableOnInteraction:false}} className="h-full">{images.map((image,index)=><SwiperSlide key={`${image}-${index}`}><div className="h-[320px] w-full bg-cover bg-center lg:h-full" style={{backgroundImage:`url(${image})`}}/></SwiperSlide>)}</Swiper><div className="pointer-events-none absolute left-0 top-0 z-10 h-full w-16 bg-[#e3262e] [clip-path:polygon(0_0,100%_0,0_100%)]"/></div></div></div><div className="grid gap-4 border-x border-b border-neutral-100 px-4 py-6 sm:grid-cols-3 lg:px-10">{items.map(it=>{const Icon=it.icon;return <div key={it.title} className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-full border border-[#e3262e]/25 text-[#e3262e]"><Icon size={20}/></span><div><h3 className="text-[12px] font-black uppercase">{it.title}</h3><p className="mt-1 text-[12px] text-neutral-500">{it.desc}</p></div></div>})}</div></div></section>}
