import { useEffect, useState } from "react";
import { Edit3, Eye, ImagePlus, Plus, Trash2 } from "lucide-react";
import { supabase } from "../../lib/supabase";
import AdminNav from "../../components/AdminNav";

const empty = { id:"", title:"", slug:"", excerpt:"", content:"", cover_image_url:"", category:"Novedades", status:"draft" };
const slugify=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

export default function AdminBlog(){
  const [posts,setPosts]=useState<any[]>([]); const [form,setForm]=useState<any>(empty); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false);
  const load=async()=>{const {data}=await supabase.from("blog_posts").select("*").order("updated_at",{ascending:false});setPosts(data??[]);}; useEffect(()=>{load();},[]);
  const save=async()=>{if(!form.title.trim()||!form.content.trim())return alert("Completa título y contenido.");setSaving(true);const payload={title:form.title.trim(),slug:form.slug.trim()||slugify(form.title),excerpt:form.excerpt.trim(),content:form.content,cover_image_url:form.cover_image_url.trim()||null,category:form.category.trim()||"Novedades",status:form.status,published_at:form.status==="published"?(form.published_at||new Date().toISOString()):null,updated_at:new Date().toISOString()};const result=form.id?await supabase.from("blog_posts").update(payload).eq("id",form.id):await supabase.from("blog_posts").insert(payload);setSaving(false);if(result.error)return alert(result.error.message);setOpen(false);setForm(empty);load();};
  const edit=(p:any)=>{setForm(p);setOpen(true);}; const remove=async(id:string)=>{if(!confirm("¿Eliminar este artículo?"))return;await supabase.from("blog_posts").delete().eq("id",id);load();};
  const uploadCover=async(file:File)=>{setUploading(true);const ext=file.name.split(".").pop()||"webp";const path=`${Date.now()}-${slugify(file.name.replace(/\.[^.]+$/, ""))}.${ext}`;const {error}=await supabase.storage.from("blog-images").upload(path,file,{upsert:false});if(error){setUploading(false);return alert(error.message);}const {data}=supabase.storage.from("blog-images").getPublicUrl(path);setForm((prev:any)=>({...prev,cover_image_url:data.publicUrl}));setUploading(false);};
  return <main className="min-h-screen bg-zinc-950 px-4 py-8 text-white xl:pl-[15.5rem]"><div className="mx-auto max-w-7xl"><div className="mb-6"><p className="text-xs font-black uppercase tracking-[.18em] text-[#e3262e]">The House of Sports</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black">Blog y noticias</h1><p className="mt-2 text-sm text-zinc-400">Publica reseñas, nuevos ingresos, guías y novedades para los clientes.</p></div><button onClick={()=>{setForm(empty);setOpen(true)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#e3262e] px-4 py-3 text-sm font-black"><Plus size={17}/>Nuevo artículo</button></div></div><AdminNav/>
  {open&&<section className="mb-6 rounded-2xl border border-white/10 bg-zinc-900 p-5"><h2 className="text-lg font-black">{form.id?"Editar artículo":"Nuevo artículo"}</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Título" className="rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm outline-none focus:border-[#e3262e]"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Categoría" className="rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm outline-none focus:border-[#e3262e]"/><input value={form.slug||""} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="Slug (opcional)" className="rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm outline-none focus:border-[#e3262e]"/><div className="flex gap-2"><input value={form.cover_image_url||""} onChange={e=>setForm({...form,cover_image_url:e.target.value})} placeholder="URL de imagen de portada" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm outline-none focus:border-[#e3262e]"/><label className="grid h-[46px] w-[46px] shrink-0 cursor-pointer place-items-center rounded-xl border border-white/10 bg-zinc-950 text-zinc-400 hover:text-[#e3262e]" title="Subir portada"><ImagePlus size={18}/><input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)uploadCover(file)}}/></label></div><textarea value={form.excerpt||""} onChange={e=>setForm({...form,excerpt:e.target.value})} placeholder="Resumen corto" className="min-h-24 rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm outline-none focus:border-[#e3262e] md:col-span-2"/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="Contenido del artículo" className="min-h-[260px] rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm leading-6 outline-none focus:border-[#e3262e] md:col-span-2"/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border border-white/10 bg-zinc-950 px-3 py-3 text-sm"><option value="draft">Borrador</option><option value="published">Publicado</option></select></div><div className="mt-4 flex gap-2">{uploading&&<span className="self-center text-xs font-bold text-zinc-500">Subiendo imagen...</span>}<button onClick={save} disabled={saving} className="rounded-xl bg-[#e3262e] px-4 py-2.5 text-sm font-black">{saving?"Guardando...":"Guardar"}</button><button onClick={()=>setOpen(false)} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-black">Cancelar</button></div></section>}
  <section className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-900"><div className="divide-y divide-white/10">{posts.length===0?<p className="p-8 text-center text-zinc-500">Aún no hay artículos.</p>:posts.map(p=><article key={p.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3">{p.cover_image_url?<img src={p.cover_image_url} className="h-14 w-20 rounded-lg object-cover"/>:<div className="h-14 w-20 rounded-lg bg-zinc-800"/>}<div className="min-w-0"><p className="text-[10px] font-black uppercase text-[#e3262e]">{p.category} · {p.status==="published"?"Publicado":"Borrador"}</p><h3 className="mt-1 truncate font-black">{p.title}</h3></div></div><div className="flex gap-2"><a href={`/blog/${p.slug}`} target="_blank" className="grid h-9 w-9 place-items-center rounded-lg border border-white/10 text-zinc-300"><Eye size={16}/></a><button onClick={()=>edit(p)} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10 text-zinc-300"><Edit3 size={16}/></button><button onClick={()=>remove(p.id)} className="grid h-9 w-9 place-items-center rounded-lg border border-red-500/20 text-red-400"><Trash2 size={16}/></button></div></article>)}</div></section></div></main>;
}
